public class Main {
    public static void main(String[] args) {
        byte apple = 83;
        System.out.println("Яблок " + apple + " кг");
        int oranges = 326;
        System.out.println("Апельсинов " + oranges + " кг");
        short watermelons = 175;
        System.out.println("Арбузов " + watermelons + " кг");
        long grapes = 1329;
        System.out.println("Винограда " + grapes + " кг");
        float tomatoes = 5.7F;
        System.out.println("Помидор " + tomatoes + " кг");
        double cucumbers = 3.87697857;
        System.out.println("Огурцов " + cucumbers + " кг");
        float a = (float) 27.12;
        System.out.println(a);
        long b = 987678965549L;
        System.out.println(b);
        double c = 2.786;
        System.out.println(c);
        int d = 569;
        System.out.println(d);
        short e = -159;
        System.out.println(e);
        int f = 27897;
        System.out.println(f);
        byte g = 67;
        System.out.println(g);
byte studentsLudmila = 23;
        System.out.println("У Людмилы Павловны " + studentsLudmila + " ученика");
        byte studentsAnna = 27;
        System.out.println("У Анны Сергеевны " + studentsAnna + " учеников");
        byte studentsKate = 30;
        System.out.println("У Екатерины Андреевны " + studentsKate + " учеников");
       int allStudents = studentsLudmila + studentsAnna + studentsKate;
        System.out.println("Всего учеников " + allStudents);
        int listStudents = 480 / allStudents;
        System.out.println("На каждого ученика рассчитано " + listStudents + " листов бумаги");
int bottle = 16;
int time = 2;
int productivity = bottle / time;
        System.out.println("За 1 минуту машина произвела " + productivity + " штук бутылок");
int times = 20;
int bottles = times * productivity;
        System.out.println("За " + times + " минут машина произвела " + bottles + " штук бутылок");
int oneDay = 24*60;
int bottleDay = oneDay * productivity;
        System.out.println("За сутки машина произвела " + bottleDay + " штук бутылок");
        int threeDays = oneDay * 3;
        int bottleThree = threeDays * productivity;
        System.out.println("За 3 дня машина произвела " + bottleThree + " штук бутылок");
        int oneMonth = oneDay * 30;
        long bottleMonth = oneMonth * productivity;
        System.out.println("За месяц " + bottleMonth + " штук бутылок");
    }
}